[theme]

# 사용자 정의 테마가 상속받을 Streamlit 기본 테마입니다.
# "light" 또는 "dark" 중 하나를 선택할 수 있습니다.
base = "light"

# 세련된 딥 블루 계열의 강조색
primaryColor = "#2C3E50"

# 부드러운 오프화이트 배경
backgroundColor = "#F5F6F8"

# 은은한 그레이 블루 계열의 보조 배경색
secondaryBackgroundColor = "#E8ECF1"

# 선명한 다크 그레이 텍스트 색상
textColor = "#2C3E50"

# 코드 블록을 제외한 앱의 모든 텍스트에 사용되는 글꼴 패밀리입니다.
# "sans serif", "serif", 또는 "monospace" 중 하나를 선택할 수 있습니다.
font = "sans serif"
